config/routes.rb
Simta2::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#index'
  resources :pages do
    get :user_profile, :on => :member
    get :news, :on => :collection
    get :wiki, :on => :collection
  end
  resources :notifications do
    get :getnotification, :on => :collection
  end
  resources :topics do
    get :tag_topic, :on => :member
    get :approve, :on => :member
    get :user, :on => :collection
  end
  resources :messages do
    get :reply, :on => :member
    get :user, :on => :collection
  end
  resources :proposals do
    get :todo, :on => :member
    post :comment, :on => :collection
    get :bimbingan_proposal, :on => :member
    get :data_mahasiswa, :on => :collection
    get :update_progress, :on => :member
    get :todo_finish, :on => :member
    get :dosen_proposal, :on => :collection
    put :update_dosen
    put :approve_dosen_assistant_proposal
  end
  devise_for :users
  
  ActiveAdmin.routes(self) do
    root :to => "admin/dashboard#index"
  end

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/views/dosen_dashboard/_bimbingan_proposal.html.haml
.span9.dashboard-element
  .navbar
    .navbar-inner.custom
      .brand-custom{"data-target" => "#bimbingan_proposal_table"} bimbingan proposal
      %ul.nav.pull-right
        %li
          %a.btn.btn-navbar-custom{:href => "/proposals"}
            .icon-tasks
            More
  #bimbingan_proposal_table.dashboard-inner
    %table.table
      - current_user.lecture_proposal.each do |f|
        %tr
          %td= link_to f.topic.title, bimbingan_proposal_proposal_path(f), :remote => true, "data-target" => "#modal_bimbingan_proposal", :role => "button", "data-toggle" => "modal", :class => "modal_bimbingan_call"
          %td= f.student.name
          %td
            - if f.progress < 30
              %span.label.label-important
                = f.progress
            - elsif f.progress < 70
              %span.label.label-warning
                = f.progress
            - elsif f.progress < 99
              %span.label.label-info
              = f.progress
            - elsif f.progress == 100
              %span.label.label-success
              = f.progress
      - current_user.assistant_proposal.where(:assistant_confirmation => true).each do |f|
        %tr
          %td= link_to f.topic.title, bimbingan_proposal_proposal_path(f), :remote => true, "data-target" => "#modal_bimbingan_proposal", :role => "button", "data-toggle" => "modal", :class => "modal_bimbingan_call"
          %td= f.student.name
          %td
            - if f.progress < 30
              %span.label.label-important
                = f.progress
            - elsif f.progress < 70
              %span.label.label-warning
                = f.progress
            - elsif f.progress < 99
              %span.label.label-info
              = f.progress
            - elsif f.progress == 100
              %span.label.label-success
              = f.progress
#modal_bimbingan_proposal.modal.hide.fade{"tabindex" => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}

app/views/dosen_dashboard/_judul_ta.html.haml
.span9.dashboard-element
  .navbar
    .navbar-inner.custom
      .brand-custom{"data-target" => "#ta_table"} Judul TA yang diajukan
      %ul.nav.pull-right
        %li
          %a.btn.btn-navbar-custom{:href => "/topics/new"}
            .icon-pencil
            Create
  #ta_table.dashboard-inner
    %table.table
      - current_user.topics.each do |f|
        %tr
          %td= link_to f.title, f
          %td= label_create f
          %td
            %p{:style => "width: 30px;"}
              = link_to edit_topic_path(f) do
                %i.icon-edit.tool-tip{:title => "edit", :rel => "tooltip"}
              = link_to topic_path(f), :method => :delete, :confirm => "apa anda yakin ?" do
                %i.icon-remove.tool-tip{:title => "remove", :rel => "tooltip"}

app/views/dosen_dashboard/_modal_proposal.html.haml
.modal-header
  %button.close{:type => "button", "data-dismiss" => "modal", "arial-hidden" => "true"} ×
  %h4= @proposal.topic.title
.modal-body
  %p
    %b Nama bimbingan :
    = @proposal.student.name
  %p
    %b Progress :
  .progress
    .bar{:style => "width: #{@proposal.progress}%;"}= "#{@proposal.progress}%"
  %p
    %b Total To do:
    = @proposal.todo_proposals.length
.modal-footer
  = link_to "lihat selengkapnya", proposals_path, :class => "btn btn-info", :target => "_blank"
  

app/views/dosen_dashboard/_permintaan_konfirmasi.html.haml
.span9.dashboard-element
  .navbar
    .navbar-inner.custom
      .brand-custom{"data-target" => "#konfirmasi_table"} Permintaan konfirmasi judul TA
  #konfirmasi_table.dashboard-inner
    %table.table
      - Topic.pending_request(current_user.id).each do |f|
        %tr{:id => "confirm_#{f.id}"}
          %td= link_to f.title, f
          %td= link_to f.tag.name, "#", :class => "pop-over", :rel => "popover", "data-content" => "#{link_to 'lihat profile',user_profile_page_path(f.tag)} <br> #{link_to 'kirim pesan', messages_path }"
          %td
            %p{:style => "width: 70px;"}
              = link_to "ya", approve_topic_path(f), :remote => true, :confirm => "apa anda yakin menerima konfirmasi ini ?", :class => "btn btn-primary btn-mini" 
              %a.btn.btn-danger.btn-mini tidak
      - current_user.assistant_proposal.where("assistant_confirmation = 0").each do |f|
        %tr{:id => "confirm_assistant_#{f.id}"}
          %td= link_to f.topic.title, f.topic
          %td= link_to "#{f.topic.tag.name} - assistant", "#", :class => "pop-over", :rel => "popover", "data-content" => "#{link_to 'lihat profile',user_profile_page_path(f.topic.tag)} <br> #{link_to 'kirim pesan', messages_path }"
          %td
            %p{:style => "width: 70px;"}
              = link_to "ya", proposal_approve_dosen_assistant_proposal_path(f,:status => "yes"), :method => "PUT", :remote => true, :confirm => "apa anda yakin menerima konfirmasi ini ?", :class => "btn btn-primary btn-mini"
              = link_to "tidak", proposal_approve_dosen_assistant_proposal_path(f,:status => "no"), :method => "PUT", :remote => true, :confirm => "apa anda yakin menolak konfirmasi ini ?", :class => "btn btn-danger btn-mini"  