config/routes.rb
Simta2::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#index'
  resources :pages do
    get :user_profile, :on => :member
    get :news, :on => :collection
    get :wiki, :on => :collection
  end
  resources :notifications do
    get :getnotification, :on => :collection
  end
  resources :topics do
    get :tag_topic, :on => :member
    get :approve, :on => :member
    get :user, :on => :collection
  end
  resources :messages do
    get :reply, :on => :member
    get :user, :on => :collection
  end
  resources :proposals do
    get :todo, :on => :member
    post :comment, :on => :collection
    get :bimbingan_proposal, :on => :member
    get :data_mahasiswa, :on => :collection
    get :update_progress, :on => :member
    get :todo_finish, :on => :member
    get :dosen_proposal, :on => :collection
    put :update_dosen
    put :approve_dosen_assistant_proposal
  end
  devise_for :users
  
  ActiveAdmin.routes(self) do
    root :to => "admin/dashboard#index"
  end

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  acts_as_taggable
  
  belongs_to :lecture_topic, :class_name => "User", :foreign_key => "lecture_id"
  belongs_to :topic_status
  belongs_to :tag, :class_name => "User", :foreign_key => "tag_id"
  # belongs_to :user_name, :class_name => "User", :foreign_key => "user_id"
  has_one :proposal
  has_many :notifications, :as => :notifiable
  has_many :attachments, :as => :attachmentable
  belongs_to :tagged, :class_name => "User", :foreign_key => "tag_id"
  attr_accessible :description, :proposal_attributes, :tag_list, :title, :lecture_id, :attachments_attributes,:tag_id, :confirmation, :topic_status_id
  
  validates_presence_of :title
  accepts_nested_attributes_for :attachments, :reject_if => proc { |attributes| attributes[:attachment_name].blank? }, allow_destroy: true
  accepts_nested_attributes_for :notifications, allow_destroy: true
  accepts_nested_attributes_for :proposal, :reject_if => proc { |attributes| attributes[:student_id].blank? and attributes[:lecture_id].blank?}, allow_destroy: true
  
  
  scope :user_writer, lambda{|params| where(:lecture_id => params)}
  scope :pending_request, lambda{|params| where("lecture_id = '#{params}' and tag_id != '' and confirmation != true")}
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  def index
    @tab = "2"
    @topics = Topic.page(params[:page]).per(10)
  end

  def show
    @tab = "2"
    @topic = Topic.find(params[:id])
  end

  def new
    @tab = "2"
    @topic = Topic.new
  end

  def create
    if !params[:topic][:proposal_attributes][:student_id].blank?
      user = user_find(params[:topic][:proposal_attributes][:student_id])
      if user
        params[:topic][:proposal_attributes][:student_id] = user.first.id
        params[:topic][:proposal_attributes][:lecture_id] = current_user.id
        params[:topic][:confirmation] = true
        params[:topic][:status_id] = 3
        params[:topic][:tag_id] = user.first.id
        user.first.update_attributes(:user_status_id => 3)
      else
        
      end
    end
    @topic = Topic.new params[:topic]
    @topic.lecture_id = current_user.id
    if @topic.save
      flash[:success] = I18n.t('topic.create.success')
      redirect_to @topic
    else
      flash[:error] = I18n.t('topic.create.error')
      render 'new'
    end
  end

  def edit
    @tab = "2"
    @topic = Topic.find(params[:id])
  end
  
  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(params[:topic])
      flash[:success] = "topik berhasil di update"
      redirect_to @topic
    else
      render 'edit'
    end
  end
  
  def tag_topic
    @topic = Topic.find(params[:id])
    if check_quote_proposal(@topic.lecture_topic)
      if @topic.update_attributes(:tag_id => current_user.id, :topic_status_id => 2)
        notification = create_notification(@topic.tag_id, @topic.lecture_id, @topic.id, @topic.class.name, I18n.t('topic.tag_topic.notification'))
        if notification
          current_user.update_column("user_status_id",2)
          flash[:success] = I18n.t('topic.tag_topic.success')
          redirect_to root_path
        end
      else
        redirect_to @topic, :flash => { :error => I18n.t('topic.tag_topic.error') }
      end
    else
      redirect_to @topic, :flash => { :error => I18n.t('default.limit_quote_proposal') }
    end
  end
  
  def approve
    @topic = current_user.topics.find(params[:id])
    if @topic.update_attributes(:confirmation => true, :topic_status_id => 3)
      proposal = Proposal.new(:student_id => @topic.tag_id, :lecture_id => @topic.lecture_id, :topic_id => @topic.id)
      if proposal.save
        notification = create_notification(@topic.lecture_id,@topic.tag_id, @topic.id, @topic.class.name, 'Permintaan TA anda disetujui silahkan upload proposal')
        if notification
           respond_to do |format|
              format.js
            end
        end
      end
    end
  end
  
  def user
    @user = User.user_topic params[:term]
    render json: @user.map(&:name)
  end
  
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= simple_nested_form_for @topic, :validate => true, :html => {:multipart => true} do |f| %>
  <%= f.input :title, :label => "Judul", :autofocus => true %>
  <%= f.input :tag_list, :label => "tag (pisahakan dengan koma)" %>
  <%= f.input :description, :label => "Deskripsi", :as => :ckeditor %>
  <a class="advanced" data-target="#advanced_proposal_form">Advanced mode</a>
  <div class="advanced_hide" id="advanced_proposal_form">
    <% @topic.build_proposal if @topic.proposal.blank? %>
    <%= f.fields_for :proposal do |n| %>
      <%= n.input :student_id,:as => :string, :placeholder => "masukkan NIM atau nama", :label => "mahasiswa yang mengerjakan", :input_html => {:data => {:autocomplete_source => user_topics_path}} %>
    <% end %>
  </div>
  <%= f.fields_for :attachments do |a| %>
    <%= render :partial => 'shared/attachment', :locals => {:n => a} %>
  <% end %>
  <p><%= f.link_to_add "Add a attachment", :attachments %></p>
  <%= f.submit "Submit", :class => "btn btn-info"%>
<% end %>

app/views/topics/approve.js.erb
$('#confirm_<%= @topic.id %>').html('<td class="alert alert-success" colspan="3"><%= @topic.title%> berhasil dikonfirmasi</td>');

app/views/topics/edit.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="page-header">
        <h2>Edit topic</h2>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="page-header">
        <h2>Topik Tugas Akhir</h2>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span3">
      <div class="well">
        <h4>Filter search</h4>
      </div>
    </div>
    <div class="span9">
      <div class="row">
        <div class="span9">
          <form class="form-search">
            <div class="input-append">
              <input type="text" class="span8 search-query">
              <button type="submit" class="btn">Search</button>
            </div>
          </form>
        </div>
      </div><!-- row -->
      <div class="row">
        <div class="span9">
          <% @topics.each do |f| %>
            <div class="row">
              <div class="span7">
                <h4><%= link_to f.title, topic_path(f) %></h4>
                <p class="subheader">Oleh <%= f.lecture_topic.name %>, di post pada tanggal <%= f.created_at.strftime('%d %B %Y') %></p>
              </div>
              <div class="span1">
                <%= label_create f %>
              </div>
            </div>
            <hr>
          <% end %>
        </div>
      </div><!-- row -->
      <div class="row">
        <div class="span9">
          <p>show <%= @topics.offset_value + 1 %> - <%= @topics.offset_value + @topics.length %> of <%= @topics.total_count %> results</p>
          <%= paginate @topics %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="page-header">
        <h2>Topik baru</h2>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="page-header">
        <h2><%= @topic.title %></h2>
        <p>Oleh <%= @topic.lecture_topic.name %>, di post pada tanggal <%= @topic.created_at.strftime('%d %B %Y') %></p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <h3>Deskripsi</h3>
      <%= raw @topic.description %>
      <% if @topic.attachments.length > 0 %>
        <h3>Lampiran</h3>
        <% @topic.attachments.each do |n| %>
          <%= link_to File.basename(n.attachment_name.to_s), n.attachment_name_url, :target => "_blank" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="span12">
      <% if can? :tag_topic, Topic %>
        <% if @topic.tag_id != nil %>
          <% if @topic.tag_id == current_user.id %>
            <%= link_to "anda telah mengambil judul ini", "#", :class => "btn btn-info disabled" %>
          <% else %>
            <% if find_no_topic_user %>
              <%= link_to "Anda sudah punya topik TA", "#", :class => "btn btn-info disabled" %>
            <% else %>
              <%= link_to "judul ini telah diambil", "#", :class => "btn btn-info disabled" %>
            <% end %>
          <% end %>
        <% else %>
          <% if find_topic_user %>
            <%= link_to "Anda sudah punya topik TA", "#", :class => "btn btn-info disabled" %>
          <% else %>
            <%= link_to "ambil sebagai judul TA", tag_topic_topic_path(@topic), :class => "btn btn-info" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>