config/routes.rb
Simta2::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#index'
  resources :pages do
    get :user_profile, :on => :member
    get :news, :on => :collection
    get :wiki, :on => :collection
  end
  resources :notifications do
    get :getnotification, :on => :collection
  end
  resources :topics do
    get :tag_topic, :on => :member
    get :approve, :on => :member
    get :user, :on => :collection
  end
  resources :messages do
    get :reply, :on => :member
    get :user, :on => :collection
  end
  resources :proposals do
    get :todo, :on => :member
    post :comment, :on => :collection
    get :bimbingan_proposal, :on => :member
    get :data_mahasiswa, :on => :collection
    get :update_progress, :on => :member
    get :todo_finish, :on => :member
    get :dosen_proposal, :on => :collection
    put :update_dosen
    put :approve_dosen_assistant_proposal
  end
  devise_for :users
  
  ActiveAdmin.routes(self) do
    root :to => "admin/dashboard#index"
  end

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/views/mahasiswa_dashboard/_proposal_index.html.haml
.span7.dashboard-element
  .navbar
    .navbar-inner.custom
      .brand-custom To dos proposal
      %ul.nav.pull-right
        %li
          %a.btn.btn-navbar-custom{:href => "/proposals/new?create=#{current_user.user_type}&proposal=#{user.id}"}
            .icon-pencil
            Create
  .dashboard-inner
    %table.table
      - if user.todo_proposals.length > 0
        - user.todo_proposals.order('created_at DESC').each do |f|
          %tr
            %td{:style => "#{'text-decoration: line-through;' if f.done == true}"}
              = link_to f.title, todo_proposal_path(f)
            %td= f.create_todo_proposal.name
            %td
              %span.label.label-info
                = f.comments.length
                comments
      -else
        %tr
          %td belum ada proposal yang di upload
    

app/views/mahasiswa_dashboard/_proposal_navbar.html.haml
.span5.dashboard-element
  .navbar
    .navbar-inner.custom
      .brand-custom Info proposal
      %ul.nav.pull-right
        %li.dropdown
          %a.dropdown-toggle{:href => "#","data-toggle" => "dropdown"}
            %i.icon-cog
          %ul.dropdown-menu
            %li
              = link_to "kirim proposal", new_proposal_path(:create => current_user.user_type, :proposal => user.id)
            %li
              = link_to "kirim pesan ke dosen", messages_path
  .dashboard-inner
    %p
      %b Judul :
      = user.topic.title
    %p
      %b Pembimbing proposal :
      = user.lecture.name
    %p
      %b progress proposal
    .progress.progress-success
      .bar{:style => "width : #{user.progress}%"}
        = "#{user.progress}%"