config/routes.rb
Simta2::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#index'
  resources :pages do
    get :user_profile, :on => :member
    get :news, :on => :collection
    get :wiki, :on => :collection
  end
  resources :notifications do
    get :getnotification, :on => :collection
  end
  resources :topics do
    get :tag_topic, :on => :member
    get :approve, :on => :member
    get :user, :on => :collection
  end
  resources :messages do
    get :reply, :on => :member
    get :user, :on => :collection
  end
  resources :proposals do
    get :todo, :on => :member
    post :comment, :on => :collection
    get :bimbingan_proposal, :on => :member
    get :data_mahasiswa, :on => :collection
    get :update_progress, :on => :member
    get :todo_finish, :on => :member
    get :dosen_proposal, :on => :collection
    put :update_dosen
    put :approve_dosen_assistant_proposal
  end
  devise_for :users
  
  ActiveAdmin.routes(self) do
    root :to => "admin/dashboard#index"
  end

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/views/layouts/_notification.html.erb
<% if notification_read > 0 %>
  <%= link_to getnotification_notifications_path, :remote => true, :class => "dropdown-toggle notification ajax active", :data => {:toggle => "dropdown"} do %>
    <p id="notification_div"><%= notification_read %></p>
  <% end %>
<% else %>
  <%= link_to getnotification_notifications_path, :remote => true, :class => "dropdown-toggle notification ajax", :data => {:toggle => "dropdown"} do %>
    <p id="notification_div"><%= notification_read %></p>
  <% end %>
<% end %>
<ul class="dropdown-menu" id="notification_pages_div">
  
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SIMTA" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.png', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"><%= image_tag "logo.png" %></a>
          <% if current_user %>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li <%= "class=active" if @tab == "1" %>><a href="/">Dashboard</a></li>
              <li <%= "class=active" if @tab == "2" %>><%= link_to "Cari judul", topics_path %></li>
              <li <%= "class=active" if @tab == "3" %>><%= link_to "wiki", wiki_pages_path %></li>
              <li <%= "class=active" if @tab == "4" %>><a href="#">About</a></li>
            </ul>
            <form class="navbar-search pull-left" action="">
              <input type="text" class="search-query span3" placeholder="Quick search">
              <div class="icon-search"></div>
            </form>
            <ul class="nav pull-right profile">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Dashboard</a></li>
                  <li><a href="#">Profile</a></li>
                  <li><%= link_to "Private messages", messages_path %></li>
                  <% if current_user.user_type == "dosen" %>
                    <li><%= link_to "buat judul baru", new_topic_path %></li>
                  <% end %>
                  <li class="divider"></li>
                  <li class="nav-header">Setting</li>
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                   <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
            </ul>
            <ul class="nav pull-right profile">
              <li><%= image_tag current_user.avatar_url(:thumb) %></li>
              <li class="dropdown" id="number_notification">
                <%= render 'layouts/notification' %>
              </li>
            </ul>
            <% else %>
            <% end %>
            
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container body">
      <div class="row">
        <div class="span12">
          <%= bootstrap_flash %>
        </div><!--/span12-->
      </div><!--/row-->
    </div><!--/container-->
    <%= yield %>
    <hr>
    <div class="container footer">
      <footer>
        <p>Copyright &copy; IT Telkom 2012</p>
      </footer>
    </div>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <div id="blink_div">
      <%= render 'layouts/blink' %>
    </div>
  </body>
</html>